const GET_ABSENCE_DATA = 'GET_ABSENCE_DATA';
const GET_USER_DATA = 'GET_USER_DATA';

const RECEIVE_ABSENCE_DATA = 'RECEIVE_ABSENCE_DATA';
const RECEIVE_USER_DATA = 'RECEIVE_USER_DATA';

const SELECT_DATE = 'SELECT_DATE';

const REQUEST_ABSENCE = 'REQUEST_ABSENCE';
const SET_ABSENCE = 'SET_ABSENCE';

export default {
  GET_ABSENCE_DATA,
  GET_USER_DATA,
  RECEIVE_ABSENCE_DATA,
  RECEIVE_USER_DATA,
  REQUEST_ABSENCE,
  SET_ABSENCE,
  SELECT_DATE,
};
